import 'package:flex_color_scheme/flex_color_scheme.dart';
import 'package:flutter/material.dart';
//import 'package:flutter/cupertino.dart';


class AppTheme {
   static ThemeData lightTheme = FlexThemeData.light(
  colors: const FlexSchemeColor( // Custom
    primary: Color(0xff766cfc),
    primaryContainer: Color(0xffd0cdfe),
    primaryLightRef: Color(0xff766cfc),
    secondary: Color(0xff3fc9b5),
    secondaryContainer: Color(0xff3fc9b5),
    secondaryLightRef: Color(0xff3fc9b5),
    tertiary: Color.fromARGB(255, 92, 67, 235),
    tertiaryContainer: Color(0xff95f0ff),
    tertiaryLightRef: Color(0xff624df7),
    appBarColor: Color(0xff3fc9b5),
    error: Color(0xfffb3b3c),
    errorContainer: Color(0xffffa2a6),
  ),
    appBarElevation: 13.0,
    fontFamily: 'Poppins',
  subThemesData: const FlexSubThemesData(
    interactionEffects: true,
    useM2StyleDividerInM3: true,
    textButtonSchemeColor: SchemeColor.secondaryContainer,
    elevatedButtonSecondarySchemeColor: SchemeColor.primaryContainer,
    outlinedButtonSchemeColor: SchemeColor.tertiary,
    outlinedButtonOutlineSchemeColor: SchemeColor.primary,
    inputDecoratorSchemeColor: SchemeColor.surfaceContainerHigh,
    inputDecoratorIsFilled: true,
    inputDecoratorBorderSchemeColor: SchemeColor.primary,
    inputDecoratorRadius: 8.0,
    inputDecoratorUnfocusedHasBorder: false,
    fabSchemeColor: SchemeColor.secondary,
    fabForegroundSchemeColor: SchemeColor.onPrimary,
    chipSchemeColor: SchemeColor.surface,
    chipSelectedSchemeColor: SchemeColor.primaryContainer,
    chipSecondarySelectedSchemeColor: SchemeColor.primary,
    chipRadius: 40.0,
    chipPadding: EdgeInsetsDirectional.fromSTEB(12, 8, 12, 8),
    alignedDropdown: true,
    dialogBackgroundSchemeColor: SchemeColor.onPrimary,
    dialogRadius: 16.0,
    appBarBackgroundSchemeColor: SchemeColor.white,
    bottomNavigationBarSelectedLabelSchemeColor: SchemeColor.primary,
    bottomNavigationBarUnselectedLabelSchemeColor: SchemeColor.outline,
    bottomNavigationBarSelectedIconSchemeColor: SchemeColor.primary,
    bottomNavigationBarUnselectedIconSchemeColor: SchemeColor.outline,
    bottomNavigationBarBackgroundSchemeColor: SchemeColor.surfaceBright,
    navigationBarIndicatorSchemeColor: SchemeColor.primaryContainer,
    navigationBarBackgroundSchemeColor: SchemeColor.surfaceContainerLowest,
    navigationRailUseIndicator: true,
    navigationRailLabelType: NavigationRailLabelType.all,
  ),
  visualDensity: FlexColorScheme.comfortablePlatformDensity,
  );

  static ThemeData darkTheme = FlexThemeData.dark(
  colors: const FlexSchemeColor( // Custom
    primary: Color(0xff5c43eb),
    primaryContainer: Color(0xffd0cdfe),
    primaryLightRef: Color(0xff766cfc),
    secondary: Color(0xff2fbea6),
    secondaryContainer: Color(0xffbaece5),
    secondaryLightRef: Color(0xff3fc9b5),
    tertiary: Color(0xff86d2e1),
    tertiaryContainer: Color(0xff004e59),
    tertiaryLightRef: Color(0xff624df7),
    appBarColor: Color(0xff3fc9b5),
    error: Color(0xffffb4ab),
    errorContainer: Color(0xff93000a),
  ),
  usedColors: 4,
  surfaceMode: FlexSurfaceMode.levelSurfacesLowScaffold,
  blendLevel: 13,
  subThemesData: const FlexSubThemesData(
    interactionEffects: true,
    blendOnColors: true,
    useM2StyleDividerInM3: true,
    textButtonSchemeColor: SchemeColor.secondaryContainer,
    elevatedButtonSecondarySchemeColor: SchemeColor.primaryContainer,
    outlinedButtonSchemeColor: SchemeColor.tertiary,
    outlinedButtonOutlineSchemeColor: SchemeColor.primary,
    inputDecoratorIsFilled: true,
    inputDecoratorRadius: 8.0,
    inputDecoratorUnfocusedHasBorder: false,
    fabSchemeColor: SchemeColor.secondary,
    fabForegroundSchemeColor: SchemeColor.onPrimary,
    chipSchemeColor: SchemeColor.surface,
    chipSelectedSchemeColor: SchemeColor.primaryContainer,
    chipSecondarySelectedSchemeColor: SchemeColor.primary,
    chipRadius: 40.0,
    chipPadding: EdgeInsetsDirectional.fromSTEB(12, 8, 12, 8),
    alignedDropdown: true,
    dialogRadius: 16.0,
    bottomNavigationBarSelectedLabelSchemeColor: SchemeColor.primary,
    bottomNavigationBarUnselectedLabelSchemeColor: SchemeColor.outline,
    bottomNavigationBarSelectedIconSchemeColor: SchemeColor.primary,
    bottomNavigationBarUnselectedIconSchemeColor: SchemeColor.outline,
    bottomNavigationBarBackgroundSchemeColor: SchemeColor.surfaceBright,
    navigationBarIndicatorSchemeColor: SchemeColor.primaryContainer,
    navigationBarBackgroundSchemeColor: SchemeColor.surfaceContainerLowest,
    navigationRailUseIndicator: true,
    navigationRailLabelType: NavigationRailLabelType.all,
  ),

  
  visualDensity: FlexColorScheme.comfortablePlatformDensity,
  );

}

